#if !defined(AFX_DIGITALDISP_H__B27068AE_8CDA_4A11_958F_F49A0C9E3CD8__INCLUDED_)
#define AFX_DIGITALDISP_H__B27068AE_8CDA_4A11_958F_F49A0C9E3CD8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


/****************************************************************************/
/*  类  名: CDigitalDisp													*/
/*  描  述: LED显示控件类									                */
/*  功  能:	以LED形式显示数据									     		*/
/*  版  本:	  												                */
/*  修改日期:				                                                */
/*  修订人:   共享代码					                                    */
/****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
// CDigitalDisp wrapper class

class CDigitalDisp : public CWnd
{
protected:
	DECLARE_DYNCREATE(CDigitalDisp)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xad630327, 0xf224, 0x11d6, { 0x81, 0x20, 0x0, 0x50, 0xfc, 0x78, 0xfd, 0xec } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	double GetNumToDisp();
	void SetNumToDisp(double);
	long GetNumAfterDot();
	void SetNumAfterDot(long);
	long GetNumBeforeDot();
	void SetNumBeforeDot(long);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DIGITALDISP_H__B27068AE_8CDA_4A11_958F_F49A0C9E3CD8__INCLUDED_)
