// dy_math.h: interface for the dy_math class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_DY_MATH_H__74F7C9E1_CF6D_11D7_ACBD_D656ADCE5160__INCLUDED_)
#define AFX_DY_MATH_H__74F7C9E1_CF6D_11D7_ACBD_D656ADCE5160__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

double IJ_ToR(double &xs,double &ys,double &xe,double &ye,double &i,double &j,bool IsG02=true);

#endif // !defined(AFX_DY_MATH_H__74F7C9E1_CF6D_11D7_ACBD_D656ADCE5160__INCLUDED_)
