//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MotorControlBench.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_BTN_ACMOTR                  101
#define IDC_BTN_DCMOTR                  102
#define IDC_BTN_INTERPOLATION           103
#define IDC_BTN_GCODE                   104
#define IDC_BTN_PARASET                 105
#define IDC_BTN_EXIT                    106
#define IDD_GCODE_FRAME                 107
#define IDC_CHARSTATIC                  108
#define IDD_INTERPEXP_FRAME             109
#define IDC_BTN_DEBUG                   114
#define IDR_MAINFRAME                   128
#define IDR_MOTORCTYPE                  129
#define IDD_FUNCTIONBAR                 130
#define IDI_ICON1                       131
#define IDI_DCMOTOR                     131
#define IDB_BITMAP2                     133
#define IDI_ICON2                       134
#define IDD_MOTORCONTROLBENCH_FORM      135
#define IDI_GCODE                       136
#define IDI_PARASET                     137
#define IDI_EXIT                        138
#define IDD_CTRLWND_DCMOTOR             139
#define IDD_CTRLWND_ACMOTOR             140
#define IDD_CTRLWND_GCODE               142
#define IDD_PAGE_PLANESEL               148
#define IDD_PAGE_ZOOMSEL                150
#define IDD_CTRLWND_INTERP              152
#define IDB_BACKGROUND                  154
#define IDI_MAP_OK                      155
#define IDD_DLG_CARDTYPE                157
#define IDI_NO                          159
#define IDB_GOOGOL                      162
#define IDD_PAGE_EXEC                   164
#define IDD_PAGE_MARK                   165
#define IDD_PAGE_TECH                   166
#define IDD_PAGE_GMODE                  167
#define IDD_PAGE_EDIT                   167
#define IDD_DLG_DEBUG                   168
#define IDI_LEDOFF                      170
#define IDI_LEDON                       172
#define IDI_RIGHT                       174
#define IDD_DLG_PARASET                 175
#define IDD_PAGE_BASEPARA               176
#define IDD_PAGE_SYSTEM_PARA            177
#define IDI_DEBUG                       179
#define IDI_INTERP                      187
#define IDD_DIALOG_PASSWORD             188
#define IDD_PAGE_JOG                    189
#define IDB_BITMAP1                     192
#define IDB_RED                         194
#define IDB_GREEN                       195
#define IDR_AVI_GOOGOL                  197
#define IDD_PAGE_FSETTING               198
#define IDD_CCD_RANGE                   199
#define IDD_CCD_LIGHT                   200
#define IDD_TABLE_DIALOG                202
#define IDD_PAGE_DOWN                   204
#define IDD_PAGE_UP                     205
#define IDD_PAGE_SYSTEM                 206
#define IDD_PAGE_MODE                   207
#define IDC_COMBO1                      1000
#define IDC_CMB_AXIS_X                  1000
#define IDC_XMAP_COMBO                  1000
#define IDC_CARDTYPE                    1000
#define IDC_AC_CTRLMODE                 1000
#define IDC_CMB_MAIN_AXIS               1000
#define IDC_CMB_INC_VALUE               1000
#define IDC_CMB_AXISNO_PARSETPAGE       1000
#define IDC_CMB_MOTORSEL                1000
#define IDC_CMB_JOG                     1000
#define IDC_COMBO2                      1001
#define IDC_CMB_AXIS_Y                  1001
#define IDC_YMAP_COMBO                  1001
#define IDC_CMB_VEL_VALUE               1001
#define IDC_CMB_AXISCOUNT               1001
#define IDC_BTN_COORD_EFFECT            1002
#define IDC_BTN_ZOOMIN                  1002
#define IDC_BTN_CHART_START             1002
#define IDC_BTN_NEW_NCCOED              1003
#define IDC_BTN_ZOOMOUT                 1003
#define IDC_BTN_CHART_STOP              1003
#define IDC_BTN_OPEN_NCCODE             1004
#define IDC_BTN_STAND                   1004
#define IDC_BTN_CHART_2                 1004
#define IDC_BTN_CHART_RESTORE           1004
#define IDC_BTN_SAVE_NCCODE             1005
#define IDC_BTN_CHART_CALCULATE         1005
#define IDC_EDIT1                       1006
#define IDC_SETKP                       1006
#define IDC_TMODE_ACC                   1006
#define IDC_VELMODE_ACC                 1006
#define IDC_GEAR_RATIO                  1006
#define IDC_SMODE_JERK                  1006
#define IDC_EDIT_KP_PARASET             1006
#define IDC_EDIT_PASSWORD               1006
#define IDC_SIZEOFREGISTER              1006
#define IDC_BTN_LOAD_NCCODE             1007
#define IDC_EDIT_DC_KI                  1007
#define IDC_ACC_EDIT                    1007
#define IDC_SETKI                       1007
#define IDC_TMODE_VEL                   1007
#define IDC_VELMODE_VEL                 1007
#define IDC_SMODE_ACC                   1007
#define IDC_EDIT_KI_PARASET             1007
#define IDC_BTN_CONTROL_RUN             1008
#define IDC_EDIT_DC_KD                  1008
#define IDC_SETKD                       1008
#define IDC_TMODE_POS                   1008
#define IDC_EDIT_KD_PARASET             1008
#define IDC_BTN_CONTROL_PAUSE           1009
#define IDC_BTN_CONTROL_STOP            1010
#define IDC_SMODE_VEL                   1010
#define IDC_BTN_CLOSEAXIS               1011
#define IDC_SMODE_POS                   1011
#define IDC_BTN_RESET                   1012
#define IDC_STATIC_FILENAME             1013
#define IDC_CMB_AXIS_Z                  1014
#define IDC_XCIR_EDIT                   1014
#define IDC_EDIT_GCODE                  1015
#define IDC_ENDX_EDIT                   1015
#define IDC_YCIR_EDIT                   1016
#define IDC_BTN_CONTROL_XHOME           1016
#define IDC_LIST_NCCODE                 1017
#define IDC_ENDY_EDIT                   1017
#define IDC_ANGLE_EDIT                  1018
#define IDC_BTN_CONTROL_YHOME           1018
#define IDC_R_EDIT                      1019
#define IDC_TAB_VIEWSELECT              1021
#define IDC_XYPLANE                     1022
#define IDC_XZPLANE                     1023
#define IDC_YZPLANE                     1024
#define IDC_AXIS1_POSITION              1024
#define IDC_AXIS2_POSITION              1025
#define IDC_TARGET_VALUE                1025
#define IDC_AXIS3_POSITION              1026
#define IDC_DISP_ACTVALUE               1026
#define IDC_SLIDER1                     1027
#define IDC_DISP_ACTVALUE2              1027
#define IDC_DEBUG_DISP_Y                1027
#define IDC_SLIDER2                     1028
#define IDC_DISP_ACTVALUE3              1028
#define IDC_DEBUG_DISP_Z                1028
#define IDC_SLIDER3                     1029
#define IDC_DISP_ACTVALUE4              1029
#define IDC_DEBUG_DISP_A                1029
#define IDC_EDIT_DC_KP                  1030
#define IDC_DEBUG_DISP_AXIS5            1030
#define IDC_AUTOZOOM                    1031
#define IDC_DEBUG_DISP_AXIS6            1031
#define IDC_SHOW_THREOY                 1032
#define IDC_STATIC_Mp                   1033
#define IDC_STATIC_Tr                   1034
#define IDC_MAP_BUTTON                  1035
#define IDC_AC_AXISON                   1035
#define IDC_BTN_GEAR_OK                 1035
#define IDC_BTN_MANUAL_XPLUS            1035
#define IDC_BTN_JOG_XPLS                1035
#define IDC_MANUALXMAX                  1036
#define IDC_AC_RUN                      1036
#define IDC_BTN_GEAR_CANCEL             1036
#define IDC_BTN_MANUAL_XMINUS           1036
#define IDC_BTN_JOG_XMIS                1036
#define IDC_INTERP_XPOSITION            1037
#define IDC_AC_AXISOFF                  1037
#define IDC_BTN_MANUAL_YPLUS            1037
#define IDC_BTN_JOG_YPLS                1037
#define IDC_SEL_COMBO                   1038
#define IDC_AC_STOP                     1038
#define IDC_BTN_MANUAL_YMINUS           1038
#define IDC_BTN_JOG_YMIS                1038
#define IDC_INTERP_YPOSITION            1039
#define IDC_BTN_MANUAL_ZPLUS            1039
#define IDC_BTN_JOG_ZPLS                1039
#define IDC_DIRECTION_RADIO             1040
#define IDC_BTN_MANUAL_ZMINUS           1040
#define IDC_BTN_JOG_ZMIS                1040
#define IDC_RADIO_CCW                   1041
#define IDC_BTN_MANUAL_APLUS            1041
#define IDC_BTN_MANUAL_AMINUS           1042
#define IDC_XMAX_COMBO                  1043
#define IDC_BTN_MANUAL_HOME             1043
#define IDC_SERVO_ON                    1044
#define IDC_BTN_MANUAL_HOME2            1044
#define IDC_BTN_MANUAL_RESET            1044
#define IDC_YMAX_COMBO                  1045
#define IDC_BTN_MANUAL_SERVON           1045
#define IDC_RUN_BUTTON                  1046
#define IDC_BTN_MANUAL_CARDINIT         1046
#define IDC_SERVO_OFF                   1047
#define IDC_STOP_BUTTON                 1048
#define IDC_VEL_EDIT                    1049
#define IDC_RADIO_AXIS1                 1050
#define IDC_BTN_PEN_ON                  1050
#define IDC_RADIO_AXIS2                 1051
#define IDC_BTN_HOME                    1051
#define IDC_BTN_AXISX_HOME              1051
#define IDC_RADIO_AXIS3                 1052
#define IDC_BTN_PEN_OFF                 1052
#define IDC_RADIO_AXIS4                 1053
#define IDC_BTN_AXISY_HOME              1053
#define IDC_TAB_AC_MODESEL              1054
#define IDC_SLIDER                      1055
#define IDC_RADIO_PROFILE               1056
#define IDC_RADIO_ACTUAL                1057
#define IDC_PASSIVEAXIS                 1057
#define IDC_LED_IN0                     1060
#define IDC_LED_IN1                     1061
#define IDC_LED_IN2                     1062
#define IDC_LED_IN3                     1063
#define IDC_LED_IN4                     1064
#define IDC_LED_IN5                     1065
#define IDC_LED_IN6                     1066
#define IDC_LED_IN7                     1067
#define IDC_LED_IN8                     1068
#define IDC_LED_IN9                     1069
#define IDC_LED_IN10                    1070
#define IDC_LED_IN11                    1071
#define IDC_LED_IN12                    1072
#define IDC_LED_IN13                    1073
#define IDC_LED_IN14                    1074
#define IDC_LED_IN15                    1075
#define IDC_SLIDER4                     1076
#define IDC_PARASET_SHEET               1077
#define IDC_RADIO_STEP                  1078
#define IDC_RADIO_SERVO                 1079
#define IDC_RADIO_DIR                   1080
#define IDC_RADIO_PULSE                 1081
#define IDC_EDIT_PPR                    1082
#define IDC_EDIT2                       1083
#define IDC_EDIT_G00_SPD                1083
#define IDC_BUTTON2                     1084
#define IDC_BTN_MANUAL_SERVOFF          1084
#define IDC_EDIT_G01_SPD                1084
#define IDC_BUTTON_YRERVERSE            1084
#define IDC_TECH_INSERT                 1084
#define IDC_BTN_NEXTPAGE                1085
#define IDC_EDIT_G00_ACC                1085
#define IDC_BTN_SHOWALL                 1086
#define IDC_EDIT_G01_ACC                1086
#define IDC_OUT_BIT0                    1087
#define IDC_BTN_CLEAR                   1087
#define IDC_DEBUG_DISP_X                1088
#define IDC_CMB_HOME                    1089
#define IDC_BTN_PREPAGE                 1090
#define IDC_STATIC_MULTI                1092
#define IDC_RADIUS_OR_STEP              1093
#define IDC_CENX_OR_SRTX                1094
#define IDC_OUT_BIT1                    1095
#define IDC_CENY_OR_SRTY                1095
#define IDC_OUT_BIT2                    1096
#define IDC_HOME_VEL                    1096
#define IDC_OUT_BIT3                    1097
#define IDC_HOME_ACC                    1097
#define IDC_OUT_BIT4                    1098
#define IDC_OUT_BIT5                    1099
#define IDC_OUT_BIT6                    1100
#define IDC_OUT_BIT7                    1101
#define IDC_OUT_BIT8                    1102
#define IDC_OUT_BIT9                    1103
#define IDC_OUT_BIT10                   1104
#define IDC_OUT_BIT11                   1105
#define IDC_OUT_BIT12                   1106
#define IDC_OUT_BIT13                   1107
#define IDC_OUT_BIT14                   1108
#define IDC_OUT_BIT15                   1109
#define IDC_AXIS1_POS                   1110
#define IDC_AXIS2_POS                   1111
#define IDC_AXIS3_POS                   1112
#define IDC_AXIS4_POS                   1113
#define IDC_GOOGOL_AVI                  1114
#define IDC_BTN_AXIS1_HOME              1115
#define IDC_BTN_AXIS2_HOME              1116
#define IDC_BTN_AXIS3_HOME              1117
#define IDC_AXIS1_NEG                   1118
#define IDC_AXIS2_NEG                   1119
#define IDC_AXIS3_NEG                   1120
#define IDC_AXIS4_NEG                   1121
#define IDC_AXIS1_HOME                  1122
#define IDC_AXIS2_HOME                  1123
#define IDC_AXIS3_HOME                  1124
#define IDC_AXIS4_HOME                  1125
#define IDC_BTN_AXIS4_HOME              1126
#define IDC_HOMESTYLE                   1127
#define IDC_AXIS1_ALARM                 1130
#define IDC_AXIS2_ALARM                 1131
#define IDC_AXIS3_ALARM                 1132
#define IDC_AXIS4_ALARM                 1133
#define IDC_AXIS3_DEBUG                 1135
#define IDC_AXIS4_DEBUG                 1136
#define IDC_AXIS1_DEBUG                 1137
#define IDC_AXIS2_DEBUG                 1138
#define IDC_AXIS5_DEBUG                 1139
#define IDC_AXIS6_DEBUG                 1140
#define IDC_CHK_FEED                    1141
#define IDC_FEEDRATIO                   1142
#define IDC_FEED_TEXT                   1143
#define IDC_PIC_STATIC                  1144
#define IDC_TAB_CONTROL                 1145
#define IDC_SHOW_IMG                    1146
#define IDC_BUTTON1                     1147
#define IDC_BUTTON_YPOSITIVE            1147
#define IDC_BUTTON_AUTO                 1147
#define IDC_BUTTON_EXEC                 1147
#define IDC_BUTTON3                     1148
#define IDC_BUTTON_XREVERSE             1148
#define IDC_BUTTON4                     1149
#define IDC_BUTTON_XPOSITIVE            1149
#define IDC_TECH_DELETE                 1149
#define IDC_SPIN1                       1158
#define IDC_LIST1                       1159
#define IDC_LIST                        1159
#define IDC_TAB1                        1160
#define IDC_CCD_TAB                     1160
#define IDC_TAB_CCD                     1160
#define IDC_SPIN2                       1162
#define IDC_EDIT3                       1163
#define IDC_SPIN3                       1165
#define IDC_EDIT4                       1166
#define IDC_SPIN4                       1167
#define IDC_BUTTON5                     1168
#define IDC_BUTTON_MODIFY               1168
#define IDC_COMBOBOXEX1                 1170
#define IDC_COMBOBOXEX2                 1171
#define IDC_EDIT_STEP                   1174
#define IDC_BUTTON_NEWFILE              1175
#define IDC_CHECK1                      1177
#define IDC_CHECK2                      1178
#define IDC_CHECK3                      1179
#define IDC_CHECK4                      1180
#define IDC_TAB_TECH                    1181
#define IDC_BUTTON6                     1182
#define IDC_BUTTON7                     1183
#define IDC_BUTTON8                     1184
#define IDC_CHECK_LEFT_IN               1185
#define IDC_CHECK_RIGHT_IN              1186
#define IDC_BUTTON_OPENFILE             1187
#define IDC_BUTTON_SAVE_FILE            1188
#define IDC_CHECK_LEFT_PROGRAM          1188
#define IDC_CHECK_RIGHT_PROGRAM         1189
#define IDC_BUTTON_NEWPOINT             1190
#define IDC_CHECK_XY                    1190
#define IDC_CHECK_Z                     1191
#define IDC_BUTTON_MARK_MODIFY          1192
#define IDC_BUTTON_SAVE                 1193
#define IDC_EDIT_CUT_SPEED              1194
#define IDC_EDIT_UP_HIGH                1195
#define IDC_EDIT_DIAMETER               1196
#define IDC_SPIN_DIAMETER               1197
#define IDC_EDIT_CONTRAST               1198
#define IDC_SPIN_CONTRAST               1199
#define IDC_EDIT_BRIGHTNESS             1200
#define IDC_SPIN_BRIGHTNESS             1201
#define IDC_BUTTON9                     1203
#define IDC_BUTTON14                    1208
#define IDC_BUTTON15                    1209
#define IDC_BUTTON16                    1210
#define IDC_BUTTON17                    1211
#define IDC_BUTTON18                    1212
#define IDC_BUTTON19                    1213
#define IDC_BUTTON20                    1214
#define IDC_BUTTON21                    1215
#define IDC_ZERO_BUTTON                 1215
#define IDC_CHECK_CLOSE_DOOR            1218
#define IDC_SHOW                        1219
#define IDC_VIEW_TEST                   1220
#define IDC_CCD_WIDTH                   1221
#define IDC_EDIT_CCD_HIGH               1222
#define IDC_CCD_HEIGHT                  1222
#define IDC_BUTTON_ZRERVERSE            1223
#define IDC_BUTTON_ZPOSITIVE            1224
#define IDC_CCD_LIGHT_ONOFF             1225
#define IDC_MAIN_AXIC                   1226
#define IDC_DUST_COLLECTOR              1227
#define IDC_LEFT_AIR_DOOR               1228
#define IDC_RIGHT_AIR_DOOR              1229
#define IDC_SPIN_CCD_WEIDTH             1230
#define IDC_SPIN_CCD_HEIGHT             1231
#define IDC_SPIN_Z_COMPENSATE           1232
#define IDC_EDIT_MILLING_DIAMETER       1233
#define IDC_SPIN_MILLING_DIAMETER       1234
#define IDC_STATIC_MILLING_DIAMETER     1235
#define IDC_TECH_MODIFY                 1236

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1237
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
